"""Project-wide constants."""
DEFAULT_TIMEZONE = "UTC"

SUPPORTED_RESOURCE_SOURCES = [
    "NASA_POWER",
    "PVGIS",
    "NSRDB",
    "ERA5",
    "CAMS",
]

SUPPORTED_SIMULATION_ENGINES = [
    "PVWATTS",
    "PVGIS",
]

DEFAULT_SYSTEM_LOSSES_PCT = 14.0
DEFAULT_DC_AC_RATIO = 1.2
DEFAULT_INVERTER_EFFICIENCY_PCT = 96.0
DEFAULT_TILT_DEG = 20.0
DEFAULT_AZIMUTH_DEG = 180.0
PVLIB_CLEAR_SKY_MODEL = "ineichen"
HOURS_PER_YEAR = 8760
