name: Deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t solaryieldlab:${{ github.ref_name }} .
      - name: Deploy to production
        run: echo "Add deployment steps here"
